@baseURL = http://localhost:8000

GET {{ baseURL }}/blogs
content-type: application/json

POST {{ baseURL }}/blogs
content-type: application/json

{
    "title": "1",
    "author": "2",
    "content": "333"
}

DELETE {{ baseURL }}/blogs/19
content-type: application/json


POST {{ baseURL }}/blogs
content-type: application/json

{
    "title": "1",
    "author": "2",
    "content": "333"
}