version: "3"

services:
  api:
    build: .
    image: novel_api
    container_name: novelApi
    restart: always
    command: yarn start
    volumes:
      - .:/novelApi
    expose:
      - 8004
    networks:
      - net
networks:
  net:
    external: true